name: e2e tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: soul_db_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 5

      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      mailhog:
        # Docker Hub image
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - run: npm ci

      - run: DB_NAME='soul_db_test' npm run migration:run

      - name: Run integration tests
        run: npm run test:e2e
