name: pr-merge tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run unit tests with coverage
        run: npm run test:cov

      - run: npm run build --if-present
